package collabmd;

import gama.sv.Project;
import javax.swing.JOptionPane;

public class Editor extends javax.swing.JInternalFrame {

	public Editor() {
		initComponents();
	}

	public Editor(String title, String contents, String path, String author, String extension) {
		initComponents();
		setTitle(title);
		editor.setText(contents);
		this.path = (path).replaceAll("/root", Project.getRoot());
		this.extension = extension;
		lbl_path.setText("path: " + this.path);
		lbl_modified.setText("[Not Modified]");
		lbl_author.setText("edited by: " + author);
		lbl_action.setText("Opened an entity");
		lbl_size.setText("size: " + contents.length() + " bytes");
	}

	public void resetModified() {
		lbl_modified.setText("[Not Modified]");
		dirty = false;
	}

	public void setAction(String text) {
		lbl_action.setText(text);
	}

	public String getExtension() { return extension; }
	public String getPath() { return path; }
	public String getText() { return editor.getText(); }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jToolBar1 = new javax.swing.JToolBar();
    lbl_path = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JToolBar.Separator();
    lbl_modified = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JToolBar.Separator();
    lbl_author = new javax.swing.JLabel();
    jSeparator3 = new javax.swing.JToolBar.Separator();
    lbl_size = new javax.swing.JLabel();
    jSeparator4 = new javax.swing.JToolBar.Separator();
    lbl_action = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    editor = new javax.swing.JTextArea();

    setClosable(true);
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("Editor");
    setVisible(true);
    addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
      public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
        formInternalFrameClosing(evt);
      }
      public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
      }
    });

    jToolBar1.setRollover(true);

    lbl_path.setText("path");
    jToolBar1.add(lbl_path);
    jToolBar1.add(jSeparator1);

    lbl_modified.setText("modified");
    jToolBar1.add(lbl_modified);
    jToolBar1.add(jSeparator2);

    lbl_author.setText("author");
    jToolBar1.add(lbl_author);
    jToolBar1.add(jSeparator3);

    lbl_size.setText("size");
    jToolBar1.add(lbl_size);
    jToolBar1.add(jSeparator4);

    lbl_action.setText("action");
    jToolBar1.add(lbl_action);

    editor.setColumns(20);
    editor.setRows(5);
    editor.setTabSize(4);
    editor.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        editorKeyTyped(evt);
      }
    });
    jScrollPane1.setViewportView(editor);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void editorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editorKeyTyped
		lbl_modified.setText("[Modified]");
		lbl_action.setText("Typed a `"  + evt.getKeyChar() + "`");
		lbl_size.setText("size: " + editor.getText().length() + " bytes");
		dirty = true;
  }//GEN-LAST:event_editorKeyTyped

  private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
		if (dirty == true) {
				int option = JOptionPane.showConfirmDialog(this, "Save before closing file`" + path + "`");
				if (option != 0)
					return ;
				Project.writeFile(path, editor.getText());
		}
  }//GEN-LAST:event_formInternalFrameClosing

	private String path; 
	private String extension;
	private boolean dirty = false;
	
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea editor;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JToolBar.Separator jSeparator1;
  private javax.swing.JToolBar.Separator jSeparator2;
  private javax.swing.JToolBar.Separator jSeparator3;
  private javax.swing.JToolBar.Separator jSeparator4;
  private javax.swing.JToolBar jToolBar1;
  private javax.swing.JLabel lbl_action;
  private javax.swing.JLabel lbl_author;
  private javax.swing.JLabel lbl_modified;
  private javax.swing.JLabel lbl_path;
  private javax.swing.JLabel lbl_size;
  // End of variables declaration//GEN-END:variables
}
