
package collabmd;

import gama.sv.Project;
import javax.swing.JDesktopPane;


public class EntityCreator extends javax.swing.JInternalFrame {

	public EntityCreator() {
		initComponents();
		note_lbl.setText("/root is currently set to " + Project.getRoot() + "/");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    fld_entity_name = new javax.swing.JTextField();
    fld_entity_path = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    fld_entity_author = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    cmb_entity_type = new javax.swing.JComboBox<>();
    btn_cancel = new javax.swing.JButton();
    javax.swing.JButton btn_finish = new javax.swing.JButton();
    error_lbl = new javax.swing.JLabel();
    note_lbl = new javax.swing.JLabel();
    jSeparator3 = new javax.swing.JSeparator();

    setClosable(true);
    setIconifiable(true);
    setTitle("Create new entity");
    try {
      setSelected(true);
    } catch (java.beans.PropertyVetoException e1) {
      e1.printStackTrace();
    }
    setVisible(true);

    jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
    jLabel1.setText("Create new entity");

    jLabel2.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
    jLabel2.setText("Entity name");

    jLabel3.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
    jLabel3.setText("Entity path");

    jLabel4.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
    jLabel4.setText("Entity author");

    jLabel5.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
    jLabel5.setText("Entity type");

    cmb_entity_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "package", "markdown", "html", "text" }));

    btn_cancel.setText("Cancel");
    btn_cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_cancelActionPerformed(evt);
      }
    });

    btn_finish.setText("Finish");
    btn_finish.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_finishActionPerformed(evt);
      }
    });

    error_lbl.setForeground(new java.awt.Color(255, 0, 0));
    error_lbl.setText(" ");
    error_lbl.setEnabled(false);

    note_lbl.setForeground(new java.awt.Color(0, 153, 0));
    note_lbl.setText("   ");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(fld_entity_name, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(fld_entity_author, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cmb_entity_type, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(note_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(fld_entity_path, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
          .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(btn_finish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cancel))
              .addComponent(error_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(0, 0, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(fld_entity_name))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(fld_entity_path))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(note_lbl)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(fld_entity_author))
        .addGap(9, 9, 9)
        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cmb_entity_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(error_lbl)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_cancel)
          .addComponent(btn_finish))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
    this.dispose();
  }//GEN-LAST:event_btn_cancelActionPerformed

  private void btn_finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finishActionPerformed
		String entity_name = fld_entity_name.getText();
		String entity_path = fld_entity_path.getText();
		String entity_author = fld_entity_author.getText();
	  String entity_type = cmb_entity_type.getItemAt(cmb_entity_type.getSelectedIndex()); 

		if (entity_name.length() == 0) {
			error_lbl.setText("*Entity name* is required ");
			error_lbl.setEnabled(true);
			return;
		}

		if (entity_path.length() == 0) {
			error_lbl.setText("*Entity path* is required ");
			error_lbl.setEnabled(true);
			return;
		}

		if (entity_author.length() == 0) {
			error_lbl.setText("*Entity author* is required ");
			error_lbl.setEnabled(true);
			return;
		}

		error_lbl.setText(" ");
		error_lbl.setEnabled(false);

		String title = entity_name; 
		String comment_start = "#"; 
		String comment_end = "#"; 
		String inner_comment = "#"; 
		String ext 	= "";
		if (entity_type.equals("markdown")) {
			title = title.concat(".md");
			ext = ".md";
		} else if (entity_type.equals("html")) {
			title = title.concat(".html");
			ext = ".html";
			comment_start = "<!--";
			comment_end = "-->";
			inner_comment = "";
		} else if (entity_type.equals("text")) {
			title = title.concat(".txt");
			ext =  ".txt";
		} else {
			return; 
		}
		
		entity_path = entity_path.concat("/" + entity_author).concat("+" + title);
		String contents = comment_start + "\n"; 
		contents += inner_comment + " entity name: \t" + title + "\n"; 
		contents += inner_comment + " entity author: \t" + entity_author + "\n"; 
		contents += inner_comment + " entity path: \t" + entity_path + "/" + title + "\n"; 
		contents += comment_end + "\n";
		
		JDesktopPane desktop = (JDesktopPane) getParent(); 
		this.dispose();
		Editor ed = new Editor(title, contents, entity_path, entity_author, ext); 
		ed.setBounds(desktop.getWidth() / 4, desktop.getHeight() / 4, ed.getWidth(), ed.getHeight());
		desktop.add(ed);
  }//GEN-LAST:event_btn_finishActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_cancel;
  private javax.swing.JComboBox<String> cmb_entity_type;
  private javax.swing.JLabel error_lbl;
  private javax.swing.JTextField fld_entity_author;
  private javax.swing.JTextField fld_entity_name;
  private javax.swing.JTextField fld_entity_path;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator3;
  private javax.swing.JLabel note_lbl;
  // End of variables declaration//GEN-END:variables
}
