package collabmd;

import gama.sv.Project;

public class PreviewBrowser extends javax.swing.JInternalFrame {

	public PreviewBrowser(String ext, String src) {
		initComponents();

		String lines = src; 
		if (ext.equals(".md")) {
			Project pr = CollabMd.getProject();
			pr.setText(src);
			lines = pr.transformLines();
			lines = "<html><body>" + lines + "<body></html>";
		}

		
		webview.setContentType("text/html");
		webview.setText(lines);
		setEditable(false);
	}

	public void setEditable(boolean value) {
		webview.setEditable(value);
	} 

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane2 = new javax.swing.JScrollPane();
    webview = new javax.swing.JEditorPane();

    setClosable(true);
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("Preview");
    setVisible(true);

    webview.setEditable(false);
    jScrollPane2.setViewportView(webview);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JEditorPane webview;
  // End of variables declaration//GEN-END:variables
}
